import { ItemData } from "./ItemData";
import { ReceiptData } from "./ReceiptData";

export class saleSave {
  tin?: string;
  bhfId?: string;
  invcNo?: number;
  orgInvcNo?: number;
  custTin?: string;
  custNm?: string;
  salesTyCd?: string;
  rcptTyCd?: string;
  pmtTyCd?: string;
  salesSttsCd?: string;
  cfmDt?: string;
  pchsDt?: string;
  salesDt: string | undefined;
  stockRlsDt?: string;
  cnclReqDt?: string;
  cnclDt?: string;
  rfdDt?: string;
  rfdRsnCd?: string;
  totItemCnt?: number;
  taxblAmtA?: number;
  taxblAmtB?: number;
  taxblAmtC?: number;
  taxblAmtD?: number;
  taxblAmtE?: number;
  taxRtA?: number;
  taxRtB?: number;
  taxRtC?: number;
  taxRtD?: number;
  taxRtE?: number;
  taxAmtA?: number;
  taxAmtB?: number;
  taxAmtC?: number;
  taxAmtD?: number;
  taxAmtE?: number;
  totTaxblAmt?: number;
  totTaxAmt?: number;
  totAmt?: number;
  prchrAcptcYn?: string;
  remark?: string;
  regrId?: string;
  regrNm?: string;
  modrId?: string;
  modrNm?: string;
  pchsTyCd?: string;
  pchsSttsCd?: string;
  regTyCd?: string;
  receipt?: ReceiptData;
  itemList?: ItemData[];
}
